version: '2'

services:
  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
      - "2181:2181"
    networks:
      custom_net:
        ipv4_address: 10.5.0.2

  kafka:
    image: wurstmeister/kafka:latest
    ports:
      - "9092:9092"
    expose:
      - "9093"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "trip-ping:1:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      custom_net:
        ipv4_address: 10.5.0.3

  postgres:
    image: 'postgres:latest'
    ports:
      - "15432:5432"
    environment:
      POSTGRES_DB: FleetTrack
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./db-data/:/var/lib/postgresql/data/
    networks:
      custom_net:
        ipv4_address: 10.5.0.4

  metabase:
    image: 'metabase/metabase:latest'
    ports:
      - "3000:3000"
    networks:
      custom_net:
        ipv4_address: 10.5.0.5

networks:
  custom_net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1